### ISSUE TITLE
error on import of new legacy release format immediate after download finished

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/dbp-same-thing-service#4]
loader_1  | Traceback (most recent call last):
loader_1  |   File "/usr/src/app/same_thing/sink.py", line 37, in load_all_parts
loader_1  |     succeeded.append(task.result())
loader_1  |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
loader_1  |     result = self.fn(*self.args, **self.kwargs)
loader_1  |   File "/usr/src/app/same_thing/sink.py", line 67, in load_part
loader_1  |     subj, _, obj = get_uris_from_line(line.decode('utf8'))
loader_1  |   File "/usr/src/app/same_thing/sink.py", line 93, in get_uris_from_line
loader_1  |     for uri in parse_triple(ntriple_line)
loader_1  |   File "/usr/src/app/same_thing/sink.py", line 87, in parse_triple
loader_1  |     return ntriple_re.search(ntriple_line).groups()

**Comment by JJ-Author** [comment]
confirmed to work on dbpedia server and @aolieman server
